### PR TITLE
Adjusted for more dynamic behaviour + Pushbullet integration instead of relying on local notifications

### PR DESCRIPTION
**Pull request by Nornode**
This is a w.i.p. 
I deactivated pidof since that isn't working on macOS (Mojave & Homebrew) 
Also the triggering script has some changes, I'd be happy to make a pull request on that too... ?

### CODE REVIEW

**Comment by wolfv6** [comment]
Oh my, that's a lot of changes for one pull request.
Please open 4 separate pull requests or issues:
- line 85: if ! ( ls -1qA $source | grep -q . ); then
  "rclone ls" is needed if source is remote e.g. Google drive
  Was "rclone ls" working OK?
- Put backups in top of $backup_remote/ directory.
  Please read rclone_jobber_tutorial.org, section ** 3) move_old_files_to.
  It shows why move_old_files_to backs up to subfolders last_snapshot/, archive/, and old_files.
- Pass in log_file path.
  Please explain the advantage of that.
- Add pushbullet.
  See if there is a way to accommodate any push_SMS, not just pushbullet (search pushbullet alternatives).
  push_SMS could be useful.
  No provider lock-in, as in the spirit of rclone not being locked into any cloud backup provider.
  Similar to monitoring_URL can be any cron-monitoring service.

**Comment by turkeyphant** [comment]
Just tested and this doesn't work on linux either. I can open two terminal prompts and run test_backup.sh in both and they both run.

**Comment by quantumicrowave** [comment]
Can confirm, still doesn't work

**Comment by donjuanmon** [comment]
Try this instead of the PID check on line 89:

`[ "${FLOCKER}" != "$0" ] && exec env FLOCKER="$0" flock -en "$0" "$0" "$@" || :`

edit
on second thought, adding the above to your job scripts makes more sense. working fine on my end

**Pull request closed without merging**
