### PR TITLE
Add a archive directory variable

### PR DESCRIPTION
**Pull request by NoLooseEnds**
Add an archive directory to keep the dated directories in to clean up a bit. Added as a variable so it’s possible to change the name.

### CODE REVIEW

**Comment by wolfv6** [comment]
There are two different ways to achieve this without changing rclone_jobber.sh
In the following examples, "archive" is the archive_dir_name.

1) in the job file:
dest="my_remote:archive"

2) when configuring the remote:
From https://rclone.org/onedrive/
Paths are specified as remote:path
eg my_remote:archive

I have not tested these.
Please let me know if they work.

**Comment by NoLooseEnds** [comment]
If I set the remote to "my_remote:archive" wouldn't everything go in that path/folder? I.e both last_snapshot and the dated directories?

The goal is to have a directory structure like this :
```
/archive
/archive/2018-04-21_23:24:13
(…)
/last_snapshot
```

**Comment by wolfv6** [comment]
So the advantage is to make finding last_snapshot easier?
I like it.
Have you tested it?

**Comment by NoLooseEnds** [comment]
Yes, in most cases it's the "last_snapshot" that you are after anyway, and with an archive directory, you don't need to list a huge amount of directories in root. This is especially nice when using tools like [rclone browser](https://github.com/mmozeiko/RcloneBrowser) and in other listing situations.

I've been running with "archive" hardcoded in the script but changed it to a variable before merging it here. My nightly backup has not yet been triggered (with the updated script), but I can't see why it shouldn't work (famous last words). I can report back tomorrow, just to be sure. 

You could even take this further, by scripting in the year, etc. … so you get /archive/year/date – because after a few years of this with backups you would potentially have a huge amount of dated directories.

**Comment by wolfv6** [comment]
Good idea.

archive_dir_name="archive/$(date +%Y)"

**Comment by NoLooseEnds** [comment]
The updated script, at least without the date part worked fine in the nights backup.

Added the year to the commit.

**Pull request merged**
